core/urls.py
from django.contrib import admin
from django.urls import path
from productos import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('log-in', views.log_in, name='log-in'),
    path('', views.log_in, name='log-in'),
    #path('sign-up/', views.sign_up , name='sign-up'),
    path('productos/', views.productos, name='productos'),
    path('log-out/', views.sign_out, name='log-out'),
    path('registrarse/', views.registrarse, name='registrarse'),
    path('producto_nuevo/', views.crear_producto, name='nuevo_producto'),
    path('lista_productos/', views.lista_productos, name='lista_productos'),
    path('producto/<int:prod_id>/', views.detalle_prod, name='detalle_prod'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/models.py
from django.db import models

# Create your models here.
class Productos(models.Model):
    nombre = models.CharField(max_length=100)
    TIPO_CHOICES = [
        ('Otros', 'Otros'),
        ('PET', 'PET'),
        ('PEAD', 'PEAD'),
        ('PEBD', 'PEBD'),
    ]

    ESTADO_CHOICES = [
        ('En Proceso', 'En Proceso'),
        ('Finalizado', 'Finalizado'),
    ]

    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES, blank=True)
    cantidad = models.IntegerField(null=True)
    descripcion = models.TextField(blank=True)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, blank=True)
    fecha_inicio = models.DateTimeField(auto_now_add=True)
    fecha_fin = models.DateTimeField(null=True , blank=True)
    imagen = models.ImageField(upload_to='productos_imagenes/', blank=True, null=True)

    def __str__(self):
        return self.nombre + ' -   -  ' + self.estado

productos/forms.py
from django.forms import ModelForm
from .models import Productos

class ProductosForm(ModelForm):
    class Meta:
        model = Productos
        fields = '__all__'

productos/views.py
from django.db import IntegrityError
from django.shortcuts import redirect, render
# cuando ejecute esto me va a retornar un formulario, y tambien un formulario de autenticacion
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# usamos la clase proporcionada por django para crear un usuario
from django.contrib.auth.models import User

# para facilitar la autenticacion y el logueo login va a encargarse de crear la cookie del usuario1
from django.contrib.auth import login, logout, authenticate


from django.http import HttpResponse


from .forms import ProductosForm
from .models import Productos





# creacion de una vista home

def home(request):
    return render(request, 'home.html')


# -------------------------------------------------------------------------------
# parte autenticacion
# -------------------------------------------------------------------------------
# vista sign_up
# -------------------------------------------------------------------------------
def sign_up(request):
    if request.method == 'GET':     
        # si visita por get muestra el formulario
        return render(request,'sign-up.html', {'form_sign_up': UserCreationForm} )
    else:
        # la vista se ejecuta por un post
        # print(request.POST)
        
        if (request.POST['password1'] == request.POST['password2']):
            
            # para interactuar con la db se debe manejar posibles errores...
            try:
                # user_instance va a tener la instancia del usuario que quiere registrarse
                user_instance = User.objects.create_user(
                    username= request.POST['username'],
                    password= request.POST['password1']
                )
            
                # guardamos esa instancia
                user_instance.save()
        
                login(request, user_instance)
        
                return redirect('productos')
            except IntegrityError: 
                        
                return render(request,'sign-up.html', {
                    'error': 'Error: Usuario ya existente.',
                    'form_sign_up': UserCreationForm
                })                       
        else:
        
            return render(request,'sign-up.html', {
                'error': 'Error: Contraseñas incorrectas.',
                'form_sign_up': UserCreationForm
            })


# -------------------------------------------------------------------------------
# login

def log_in(request):
    if (request.method == 'GET'):
        return render(request, 'log-in.html', { 'form': AuthenticationForm })
    else:
        # caso de que venga por otro metodo http
        print(request.POST)
        # se guarda en usuario el resultado de la autenticacion
        usuario = authenticate(request, 
            username= request.POST['username'],
            password= request.POST['password']
        )
        
        if usuario is None:
            return render(request,
                'log-in.html',
                { 'form': AuthenticationForm, 'error': 'Error: Usuario o contraseña incorrectos.' }
            )
        else:
            login(request, usuario)
            return redirect('lista_productos')
        

    


# -------------------------------------------------------------------------------
# logout

def sign_out(request):
    logout(request)
    return redirect('log-in')






# -------------------------------------------------------------------------------
# Parte de productos
# -------------------------------------------------------------------------------

def productos(request):

    return render(request, 'productos.html')


def registrarse(request):
    if request.method == 'GET':
        return render(request, 'registrarse.html', {"form": UserCreationForm})
    else:

        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    username=request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                return redirect('productos')
            except IntegrityError:
                return render(request, 'registrarse.html', {"form": UserCreationForm, "error": "Username already exists."})

        return render(request, 'registrarse.html', {"form": UserCreationForm, "error": "Passwords did not match."})



def crear_producto(request):
    if request.method == "GET":
        return render(request, 'crear_producto.html', {"form": ProductosForm})
    else:
        try:
            form = ProductosForm(request.POST, request.FILES)
            nuevo_producto = form.save(commit=False)
            nuevo_producto.save()
            return redirect('productos')
        except ValueError:
            return render(request, 'Productos.html', {"form": ProductosForm, "error": "Error creando producto."})


def lista_productos(request):
    lista = Productos.objects.all
    return render(request, 'lista_productos.html', {"lista": lista})


def detalle_prod(request, prod_id):
    prod = Productos.objects.get(pk=prod_id)
    return render(request, 'detalle_producto.html' , {'prod': prod})

productos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TPI Diseño</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    />
  </head>
  <body p style="font-family: 'Roboto', sans-serif">
    <nav
      class="navbar navbar-expand-lg navbar-dark"
      style="background-color: #198754"
    >
      <div class="container">
        {% if user.is_authenticated %}
        <b class="navbar-brand">Reciplas</b>
        {% else %}
        <a class="navbar-brand" href="/"><b>Reciplas</b></a>
        {% endif %}

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
              href="{% url 'lista_productos' %}"
              class="nav-link"
              style="color: aliceblue"
                >Catalogo</a
              >
            </li>
            <!-- <li class="nav-item">
              <a
              href="{% url 'nuevo_producto' %}"
              class="nav-link"
              style="color: aliceblue"
              >Agregar Producto</a
              >
            </li> -->
            <li class="nav-item">
              <a
              href="{% url 'log-out'%}"
              class="nav-link"
              style="color: aliceblue"
              >Salir</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'log-in' %}" class="nav-link">Ingresar</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'registrarse' %}" class="nav-link">Registrarse</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock content %}
  </body>
</html>

productos/templates/crear_producto.html
{% extends 'base.html' %} {% block content %}
<main class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card" style="border-color: #198754">
        <div class="card-header text-white" style="background-color: #198754">
          <h1 class="card-title mb-0">Nuevo Producto</h1>
        </div>
        <div class="card-body">
          {{ error }}
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-3">
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="id_nombre" class="form-label">Nombre</label>
                  <input
                    type="text"
                    id="id_nombre"
                    name="nombre"
                    class="form-control"
                  />
                </div>

                <!-- es el input del campo tipo -->
                <div class="col-md-6">
                  <div class="mb-3">
                    <label for="id_tipo" class="form-label">Tipo</label>
                    <select id="id_tipo" name="tipo" class="form-select">
                      <option value="" selected disabled>
                        Selecciona un tipo
                      </option>
                      {% for choice in form.tipo.field.choices %}
                      <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <!-- fin del input tipo -->

                <div class="mb-3">
                  <label for="id_fecha_fin" class="form-label"
                    >Fecha de Fin</label
                  >
                  <input
                    type="date"
                    id="id_fecha_fin"
                    name="fecha_fin"
                    class="form-control"
                  />
                </div>
                <div class="mb-3">
                  <label for="id_cantidad" class="form-label">Cantidad</label>
                  <input
                    type="number"
                    id="id_cantidad"
                    name="cantidad"
                    class="form-control"
                    oninput="validarCantidad(this)"
                  />

                  <!-- script para que no se ingresen numeros negativos -->                  
                  <script>
                    function validarCantidad(input) {
                      if (input.value < 1) {
                        input.value = 1; // Si el valor es negativo, establecerlo como cero
                      }
                    }
                  </script>
                
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="descripcion" class="form-label"
                    >Descripción del producto</label
                  >
                  <textarea
                    id="descripcion"
                    name="descripcion"
                    rows="4"
                    class="form-control"
                    style="outline: solid 1px #198754"
                  ></textarea>
                </div>
                <div class="mb-3">
                  <label for="id_imagen" class="form-label">Imagen</label>
                  <input
                    type="file"
                    id="id_imagen"
                    name="imagen"
                    class="form-control"
                    style="
                      border: solid 2px #198754;
                      background-color: aliceblue;
                    "
                  />
                </div>
              </div>
            </div>
            <div class="d-grid">
              <button
                type="submit"
                class="btn btn-primary"
                style="background-color: #198754; border: none"
              >
                Agregar Producto
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

productos/templates/detalle_producto.html
{% extends 'base.html' %} {% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card" style="border: solid 2px #198754; border-radius: 10px">
        <div class="card-header" style="background-color: #198754">
          <h1 class="card-title text-white mb-0">Detalles del Producto</h1>
        </div>
        <div
          class="card-body"
          style="border-radius: 2px; border: solid 2px #198754"
        >
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                <br />
                {% if prod.imagen %}
                <img
                  src="{{ prod.imagen.url }}"
                  alt="{{ prod.nombre }}"
                  class="img-fluid rounded shadow"
                  style="max-height: 300px"
                />
                {% else %}
                <p class="text-muted">No hay imagen disponible</p>
                {% endif %}
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <h6>ID producto</h6>
                <p class="fw-bold">{{ prod.id }}</p>
              </div>
              <div class="mb-3">
                <h6>Nombre producto</h6>
                <p class="fw-bold">{{ prod.nombre }}</p>
              </div>
              <div class="mb-3">
                <h6>Cantidad producto</h6>
                <p class="fw-bold">{{ prod.cantidad }}</p>
              </div>
              <div class="mb-3">
                <h6>Descripción del producto</h6>
                <p>{{ prod.descripcion }}</p>
              </div>
              <div class="mb-3">
                <h6>Fecha de inicio</h6>
                <p class="fw-bold">{{ prod.fecha_inicio }}</p>
              </div>
              <div class="mb-3">
                <h6>Fecha de fin</h6>
                <p class="fw-bold">{{ prod.fecha_fin }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{{ error }} {% endblock %}

productos/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Home
</h1>
{% endblock content %}

productos/templates/lista_productos.html
{% extends 'base.html' %} {% block content %}

<h1>Lista de Productos</h1>

<ul>
  {% for prod in lista %}
  <li>
    <main class="conteiner py-5">
      <section class="card card-body">
        <a href="{% url 'detalle_prod' prod.id %}">
          {% if prod.cantidad == none %}
          <h5 class="text-danger"><strong>{{prod.nombre}}</strong></h5>
          {% else %}
          <h5>{{prod.id}} {{prod.nombre}} {{prod.cantidad}}</h5>
          {% endif %}
          <p>{{prod.descripcion}}</p>

          {{prod.fecha_inicio|date:'M j Y:i'}}
        </a>
      </section>
    </main>
  </li>
  {% endfor %}
</ul>

{% endblock %}

productos/templates/log-in.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center mb-4">Hola de nuevo!</h1>

      <div class="card">
        <div class="card-body">
          <span style="color: rgb(112, 22, 22)" class="text-danger">
            <b>{{ error }}</b>
          </span>
          
          <form action="{% url 'log-in' %}" method="post">
            {% csrf_token %}
            
            <div class="mb-3">
              <label for="username" class="form-label">Usuario</label>
              <input type="text" name="username" id="usuario" class="form-control">
            </div>
            
            <div class="mb-3">
              <label for="password" class="form-label">Contraseña</label>    
              <input type="password" name="password" id="password" class="form-control">
            </div>
            <div class="container mt-5">

              <div class="d-grid">
                <button class="btn btn-success">Ingresar</button>  
              </div>
            
            </div>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

productos/templates/productos.html
{% extends 'base.html' %}

{% block content %}
<h1>Productos</h1>

<p></p>
{% endblock content %}

productos/templates/registrarse.html
{% extends 'base.html' %} {% block content %}

<div class="container">

  {{error}}

  <form action="{% url 'registrarse' %}" method="POST">
    {% csrf_token %}

    <div class="container mt-5">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <h1 class="text-center mb-4">Registrar un nuevo usuario</h1>

          <div class="card" style="outline-color: #198754;">
            <div class="card-body" style="outline-color: #198754;">
              <span style="color: rgb(112, 22, 22)" class="text-danger">
                <b>{{ error }}</b>
              </span>

              <form action="{% url 'log-in' %}" method="post">
                {% csrf_token %}

                <div class="mb-3">
                  <label for="username" class="form-label">Nombre de usuario</label>
                  <input
                    type="text"
                    name="username"
                    id="usuario"
                    class="form-control"
                  />
                </div>

                <div class="mb-3">
                  <label for="password" class="form-label">Ingrese una Contraseña</label>
                  <input
                    type="password"
                    name="password1"
                    id="password"
                    class="form-control"
                  />
                </div>

                <div class="mb-3">
                  <label for="password" class="form-label">Repita la Contraseña</label>
                  <input
                    type="password"
                    name="password2"
                    id="password"
                    class="form-control"
                  />
                </div>

                <div class="container mt-5">
                  <div class="d-grid">
                    <button class="btn btn-success">Registrarse</button>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

productos/templates/sign-up.html
{% extends 'base.html' %}

{% block content %}
<h1><i>INGRESAR</i></h1>
<p style="color: rgb(107, 33, 33);">
    <b>{{ error }}</b>
</p>
<form action="{% url 'sign-up' %}" method="post">
    {% csrf_token %}
    
    {{ form_sign_up.as_p}}

    <button>Enviar</button>
</form>
{% endblock content %}